ecosystems = [
  "GIT",

  ### Not included:
  ## Maybe support these later
  # "AlmaLinux",
  # "Alpine",
  # "Android",
  # "Bitnami",
  # "CRAN",
  # "Debian",
  # "GSD",
  # "GitHub Actions",
  # "Go",
  # "Hackage",
  # "Hex",
  # "Maven",
  # "NuGet",
  # "OSS-Fuzz",
  # "Packagist",
  # "Pub",
  # "PyPI",
  # "Rocky Linux",
  # "RubyGems",
  # "SwiftURL",
  # "UVI",
  # "Ubuntu",
  # "crates.io",
  # "npm",

  ## Doesn't contain real vulnerabilities, only automated entries
  ## seemingly based on commits marked as improving security
  # "Linux",
]

data_path = "~/.cache/repovul"
