ecosystems = [
  "AlmaLinux",
  "Alpine",
  "Android",
  "Bitnami",
  "CRAN",
  "Debian",
  "GIT",
  "GSD",
  "GitHub Actions",
  "Go",
  "Hackage",
  "Hex",
  "Linux",
  "Maven",
  "NuGet",
  "OSS-Fuzz",
  "Packagist",
  "Pub",
  "PyPI",
  "Rocky Linux",
  "RubyGems",
  "SwiftURL",
  "UVI",
  "Ubuntu",
  "crates.io",
  "npm",
]

data_path = "~/.cache/repovul"
